In [1]:
import tensorflow as tf
import numpy as np

xy = np.loadtxt('train.txt', unpack=True, dtype='float32')
x_data = np.transpose(xy[0:3])
y_data = np.transpose(xy[3:])

# tf Graph input
X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])

# Set model weight
W = tf.Variable(tf.zeros([3, 3]))

# Construct model
hypothesis = tf.nn.softmax(tf.matmul(X, W))

# Minimize error using cross entropy
learning_rate = 0.002

# Cross entropy
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), reduction_indices=1))

# Gradient descent
optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)

# Initializing the variables
init = tf.initialize_all_variables()

# Launch the graph
with tf.device('/gpu:0'):
    with tf.Session() as sess:
        sess.run(init)

        for step in xrange(2001):
            sess.run(optimizer, feed_dict={X:x_data, Y:y_data})

            if step % 200 == 0:
                print step, sess.run(cost, feed_dict={X:x_data, Y:y_data})
                print sess.run(W)
                print '\n'
                
# Test & one-hot encoding
        print '\n'
        a = sess.run(hypothesis, feed_dict={X:[[1, 11, 7]]})
        print a, sess.run(tf.arg_max(a, 1))
        
        b = sess.run(hypothesis, feed_dict={X:[[1, 3, 4]]})
        print b, sess.run(tf.arg_max(b, 1))
        
        c = sess.run(hypothesis, feed_dict={X:[[1, 1, 0]]})
        print c, sess.run(tf.arg_max(c, 1))
        
        print '\n'
        all = sess.run(hypothesis, feed_dict={X:[[1, 11, 7], [1, 3, 4], [1, 1, 0]]})
        print all, sess.run(tf.arg_max(all, 1))

Instructions for updating:
Use `tf.global_variables_initializer` instead.
0 1.09689
[[ -1.66666650e-04   8.33333252e-05   8.33332961e-05]
 [  3.33333330e-04   5.83333429e-04  -9.16666759e-04]
 [  3.33333446e-04   8.33333412e-04  -1.16666663e-03]]


200 1.0498
[[-0.0429384  -0.00628553  0.04922393]
 [ 0.01748881  0.00151359 -0.0190024 ]
 [ 0.0183315   0.04961048 -0.06794202]]


400 1.0319
[[-0.08745275 -0.01732175  0.10477452]
 [ 0.02112651 -0.01801384 -0.00311266]
 [ 0.02397988  0.07204235 -0.09602229]]


600 1.01543
[[-0.13112612 -0.02836881  0.15949482]
 [ 0.02410537 -0.03502426  0.01091891]
 [ 0.02984627  0.09165264 -0.12149903]]


800 1.00017
[[-0.17394163 -0.03936481  0.21330631]
 [ 0.02668835 -0.04969865  0.02301032]
 [ 0.03598925  0.10892199 -0.14491135]]


1000 0.985951
[[-0.21592051 -0.05028179  0.26620212]
 [ 0.02895593 -0.06232976  0.03337386]
 [ 0.04231581  0.12414306 -0.16645889]]


1200 0.972626
[[-0.2570864  -0.06109593  0.31818214]
 [ 0.03097591 -0.0731765   0.04220062]